export class EnvironmentTag {
  
}

export enum Tag {
  BALADA = 'Uy, hecho el Moreli@ ha estado',
  CUMBIA = 'Ponga a bailar a los mijines!',
  BINGLES = 'Hecho el gring@ te veo, queriendo cantar en ingles',
  RUMBA = 'Ole! Ya te salio lo español!',
  ROCK = 'Siempre hay algunito hecho el rico',
  BOLERO = 'Uy, hecho el Moreli@ ha estado',
  RANCHERA = 'Que? Hecho el mexicano, anda a pagar la pared mejor',
  PASILLO = 'Con la vena abierta has estado',
  TONADA = 'Ques pues, ni haz de saber que tipo de musica es esta',
  ROCKOLERA = 'Enseguida con la corta venas',
  BACHATA = 'Que muy caribeño!',
  DISCO = 'Ya estas viejo ve Tu abuelito cantaba esta cancion',
  PROTESTA = 'Hecho el rebelde te noto',
  SALSA = 'Que? Muy salsa?!',
  VALLENATO = 'Parce, haga rapido esta vuelta o que',
  MERENGUE = 'Ya va, hecho el caribeño',
  VALS = 'Hecho el de la realeza te noto',
  FOLCKLORICA = 'La misma musica de tus papas te ha gustado',
  POP = 'Ya vas a decir que eres milenial…anda ve viejito',
  ALBAZO = 'Iiiiissseeee! Extrañando la llacta estas',
  SANJUANITO = 'Iiiiissseeee! Extrañando la llacta estas',
  MAMBO = 'Ya va, hecho el caribeño',
  SAMBA = 'Hecho el Brasiler@, ni la calle Brasil conoces',
  RAP = 'Ya has de decir que puedes rapear!',
  PASACALLE = 'Iiiiissseeee! Extrañando la llacta estas',
  FLAMENCO = 'Ole! Ya te salio lo español!',
  ZAMBA = 'Che, mira vos, no me rompas las bolas',
  REGGAETON = 'Ya has de decir que sabe perreo',
  BOMBA = 'Si solo conoces Tonsupa, ya hecho el que sabe Bomba',
  YARAVI = 'Iiiiissseeee! Extrañando la llacta estas',
  ROCKROLL = 'Siempre hay algunito hecho el rico',
  CORRIDO = 'Que? Hecho el mexicano, anda a pagar la pared mejor',
  TECHNO = 'Que muy Depeche Mode, anda!!',
  NACIONAL = 'Iiiiissseeee! Extrañando la llacta estas',
  TANGO = 'Che, mira vos, no me rompas las bolas',
  REGGAE = 'Ya te has de haber pegado la guardada',
  TEXMEX = 'Hecho el gringo-mexicano, ya le llamo a migra de una',
  TROVA = 'Hecho el rebelde te noto, y encima Castrista',
  INFANTIL = 'Vea Guaguito, deje a los mayores cantar',
  PASODOBLE = 'Ole! Ya te salio lo español!',
  BANDA = 'Que? Hecho el mexicano, anda a pagar la pared mejor',
  ELECTRONICA = 'Que muy Depeche Mode, anda!!',
  TRIBAL = 'Que? Hecho el mexicano, anda a pagar la pared mejor',
  BLUES = 'Hecho el gring@ te veo, queriendo cantar en ingles. Y encima Moreli@',
  MUNDIAL = 'Que muy futbolero?!',
  BALADAINGLES = 'Hecho el gring@ te veo, queriendo cantar en ingles',
  LLANERA = 'Ya le voy a llamar al Maduro veras',
}
