#!/bin/bash

GIT_CONFIG=".gitconfig"
NPM_CONFIG=".npmrc"
ORIG_POSTFIX="_ORIG"
NEW_POSTFIX=""

GIT_OLD_NAME="$USERPROFILE/$GIT_CONFIG"
GIT_NEW_NAME="$USERPROFILE/$GIT_CONFIG$ORIG_POSTFIX"

NPM_OLD_NAME="$USERPROFILE/$NPM_CONFIG"
NPM_NEW_NAME="$USERPROFILE/$NPM_CONFIG$ORIG_POSTFIX"


if [ -n "$1" ] && [ "$1" = "-r" ]; then
    GIT_OLD_NAME="$USERPROFILE/$GIT_CONFIG$ORIG_POSTFIX"
    GIT_NEW_NAME="$USERPROFILE/$GIT_CONFIG"

    NPM_OLD_NAME="$USERPROFILE/$NPM_CONFIG$ORIG_POSTFIX"
    NPM_NEW_NAME="$USERPROFILE/$NPM_CONFIG"
fi

echo "Renaming git config file..."
mv -v -f $GIT_OLD_NAME $GIT_NEW_NAME

echo "Renaming npm config file..."
mv -v -f $NPM_OLD_NAME $NPM_NEW_NAME